### PR TITLE
add lock for reassigning partition to new consumer

### PR DESCRIPTION
**Pull request by yitian108**
When I try to test peer to peer consume using sarama library, some codes snippet like this:

```go
func TestP2P(topic string) {
	if err := NewConsumer(topic, P2PConsumer1); err != nil {
		// some logs
	}

	if err := NewConsumer(topic，P2PConsumer2); err != nil {
		// some logs
	}
	
	stop := false
	count := 0
	go func() {
		for {
			if !stop {
				count++
				msg := "test p2p msg: " + strconv.Itoa(count)
				NewProducer(topic，[]byte(msg))
			}
			time.sleep(time.Second)			
		}
	}()

	select {}
}
```

Sometimes, running this code will report the panic 'concurrent map writes', and the location of panic points to the method 'addPartitionMovementRecord' in balance_strategy.go, so I add the lock for concurrently running the multiple consumers access the same new partition.

Please check it.

lockMap

### CODE REVIEW

**Comment by yitian108** [comment]
hello @dnwe, I've modify some codes that only lock one map in the partitionMovements, and the commit of the branch lock-for-adding-partition is 9913274 , hopefully, the newer could be pass all checks.

**Comment by dnwe** [comment]
@yitian108 are you using NewBalanceStrategySticky for each of your consumers rather than the deprecated shared global of BalanceStrategySticky? They should already have a unique partitionMovements instance if so:

https://github.com/IBM/sarama/blob/fb814087d8d76fe9f48fcb415f8118543a52e064/balance_strategy.go#L107-L112

**Comment by yitian108** [comment]
Hi @dnwe , I used the following api for each consumer:

```go
config.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategySticky
```

Is this global of BalanceStrategySticky? If that, How should I use the NewBalanceStrategySticky at the starting of config kafka?

ps: I am using the samara version 1.37, which new version using the NewBalanceSTrategySticky?

**Comment by dnwe** [comment]
It was `fix: prevent data race in balance strategy` by @napallday from https://github.com/IBM/sarama/pull/2453 included in the latest https://github.com/IBM/sarama/releases/tag/v1.40.0

**Comment by yitian108** [comment]
Thanks @dnwe and @napallday, I'll try to use NewBalanceStrategyRange() instead to test the case.

**Comment by yitian108** [comment]
Hi @dnwe @napallday, I try to use NewBalanceStrategySticky() as below
```go
	config := sarama.NewConfig()
	config.Consumer.Group.Rebalance.Strategy = sarama.NewBalanceStrategySticky()
```
However, the IDE GoLand prompts "'Strategy' is deprecated", it seems that I used the wrong way to achive the object, do you have another good way to implement the requirement?

**Comment by napallday** [comment]
hi @yitian108, it's expected. From Sarama v1.37.0(more precisely PR #2339 ), `config.Consumer.Group.Rebalance.Strategy` is deprecated and `config.Consumer.Group.Rebalance.GroupStrategies` is preferred for supporting specifying multiple balance strategies.

**Comment by yitian108** [comment]
Thanks @napallday , to my understand, I should  use like this `config.Consumer.Group.Rebalance.GroupStrategies = []sarama.BalanceStrategy{sarama.NewBalanceStrategySticky(), sarama.NewBalanceStrategyRoundRobin()}`, and if only one strategy would be applied, it looks like `config.Consumer.Group.Rebalance.GroupStrategies = []sarama.BalanceStrategy{sarama.NewBalanceStrategySticky()}`, right?

**Comment by napallday** [comment]
correct! @yitian108

**Pull request closed without merging**
