### PR TITLE
fix: data race in Broker.AsyncProduce

### LINKED ISSUE #2673: data race found in the async producer
##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|  v1.41.2      |       |1.21.2     |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```

==================
WARNING: DATA RACE
Read at 0x00c003b01470 by goroutine 2265:
  github.com/IBM/sarama.(*Broker).AsyncProduce()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/broker.go:437 +0x5d
  github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func1()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:829 +0x264
  github.com/IBM/sarama.withRecover()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/utils.go:43 +0x41
  github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func4()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:794 +0x33

Previous write at 0x00c003b01470 by goroutine 2262:
  github.com/IBM/sarama.(*Broker).Open()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/broker.go:181 +0x3d2
  github.com/IBM/sarama.(*client).cachedLeader()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/client.go:891 +0x2cf
  github.com/IBM/sarama.(*client).LeaderAndEpoch()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/client.go:501 +0x64
  github.com/IBM/sarama.(*client).Leader()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/client.go:492 +0x44
  github.com/IBM/sarama.(*nopCloserClient).Leader()
      <autogenerated>:1 +0x6a
  github.com/IBM/sarama.(*partitionProducer).dispatch()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:632 +0xe7
  github.com/IBM/sarama.(*partitionProducer).dispatch-fm()
      <autogenerated>:1 +0x33
  github.com/IBM/sarama.withRecover()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/utils.go:43 +0x41
  github.com/IBM/sarama.(*asyncProducer).newPartitionProducer.func1()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:600 +0x33

Goroutine 2265 (running) created at:
  github.com/IBM/sarama.(*asyncProducer).newBrokerProducer()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:794 +0x690
  github.com/IBM/sarama.(*asyncProducer).getBrokerProducer()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:1343 +0x11d
  github.com/IBM/sarama.(*partitionProducer).dispatch()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:634 +0x1a9
  github.com/IBM/sarama.(*partitionProducer).dispatch-fm()
      <autogenerated>:1 +0x33
  github.com/IBM/sarama.withRecover()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/utils.go:43 +0x41
  github.com/IBM/sarama.(*asyncProducer).newPartitionProducer.func1()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:600 +0x33

Goroutine 2262 (running) created at:
  github.com/IBM/sarama.(*asyncProducer).newPartitionProducer()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:600 +0x410
  github.com/IBM/sarama.(*topicProducer).dispatch()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:510 +0x1ba
  github.com/IBM/sarama.(*topicProducer).dispatch-fm()
      <autogenerated>:1 +0x33
  github.com/IBM/sarama.withRecover()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/utils.go:43 +0x41
  github.com/IBM/sarama.(*asyncProducer).newTopicProducer.func1()
      /go/pkg/mod/github.com/!i!b!m/sarama@v1.41.2/async_producer.go:495 +0x33
==================

```

</p>
</details>

### PR DESCRIPTION
**Pull request by lzakharov**
Closes #2673

### CODE REVIEW

**Comment by bmassemin** [comment]
This fix would help stabilize our production producers. Thanks!

**Comment by Mateusnasciment** [comment]
remove whitespace

**Review by prestona — APPROVED** [review]
These changes look good to me.

**Review by prestona — CHANGES_REQUESTED** [review]
Actually - on reflection, I wonder if it would be better to wrap the Lock/Unlock around the assignment from `b.metricsRegistry`, as I think the current changes have the potential to hold the lock while the user-supplied callback is invoked (which Sarama doesn't have any control over how long this takes, or if this tries to re-enter part of Sarama that also uses the lock).

**Review by prestona — APPROVED** [review]
Argh! No. Actually the invocations to the callback are wrapped into the promise, so they won't be invoked directly from within AsyncProduce code while the lock is held.🤦

**Comment by lzakharov** [comment]
@prestona sorry for disturbing, can we merge it now?

**Comment by prestona** [comment]
@lzakharov - np. Merged.

**Pull request merged**
