### PR TITLE
feat: export NewKerberosClientFunc to config for allow custom client

### PR DESCRIPTION
**Pull request by fooofei**
## what this pr is 

The new pr is a custom config enhancement that allows the creation of user-defined KerberosClient.

After allow custom NewKerberosClientFunc, then we can custom spn, this also will satisfy https://github.com/IBM/sarama/pull/2437/files
## how to implement 

move `NewKerberosClientFunc` from `GSSAPIKerberosAuth` private field to `GSSAPIConfig` public field, allow user set `NewKerberosClientFunc` from config struct.

## tests result

```
?       github.com/IBM/sarama/internal/toxiproxy        [no test files]
?       github.com/IBM/sarama/tools/kafka-console-consumer      [no test files]
?       github.com/IBM/sarama/tools/kafka-console-partitionconsumer     [no test files]
?       github.com/IBM/sarama/tools/kafka-console-producer      [no test files]
?       github.com/IBM/sarama/tools/kafka-producer-performance  [no test files]
?       github.com/IBM/sarama/tools/tls [no test files]
ok      github.com/IBM/sarama   31.257s
ok      github.com/IBM/sarama/mocks     (cached)
```

### CODE REVIEW

**Comment by fooofei** [comment]
@dnwe  can you check this pr ？

**Comment by dnwe** [comment]
@fooofei whilst the change looks simple on paper, it's technically a change to public facing APIs:

- GSSAPIConfig: old is comparable, new is not
- GSSAPIKerberosAuth.NewKerberosClientFunc: removed

So we need to have a think about whether anyone in reality could have been relying on the previous APIs and hence how we can best handle this change

**Comment by fooofei** [comment]
GSSAPIConfig comparable is meaning-less, no need to compare
GSSAPIKerberosAuth is used at type Broker struct  as private field kerberosAuthenticator, so remove GSSAPIKerberosAuth.NewKerberosClientFunc is safe.

**Comment by fooofei** [comment]
expect to response/please response 6

**Comment by fooofei** [comment]
please response 7

**Pull request closed without merging**
