### PR TITLE
feat: add BuildSpnFunc to GSSAPIConfig for allow custom spn

### PR DESCRIPTION
**Pull request by fooofei**
## what this pr is 

The new pr is a custom config enhancement that allows the creation of custom spn build.

After allow custom spn build, this also will satisfy #2437
## how to implement 

add a function type  `type BuildSpnFunc func(serviceName, host string) string`

add a field `BuildSpn BuildSpnFunc` to `type GSSAPIConfig struct`

then user can set a custom `BuildSpn`

## tests result

```
?       github.com/IBM/sarama/internal/toxiproxy        [no test files]
?       github.com/IBM/sarama/tools/kafka-console-consumer      [no test files]
?       github.com/IBM/sarama/tools/kafka-console-partitionconsumer     [no test files]
?       github.com/IBM/sarama/tools/kafka-console-producer      [no test files]
?       github.com/IBM/sarama/tools/kafka-producer-performance  [no test files]
?       github.com/IBM/sarama/tools/tls [no test files]
ok      github.com/IBM/sarama   31.257s
ok      github.com/IBM/sarama/mocks     (cached)
```

### CODE REVIEW

**Comment by fooofei** [comment]
hi @dnwe @hindessm

**Comment by dnwe** [comment]
@fooofei thanks for the PRs, we have seen them and don’t worry we will get around to reviewing both, it isn’t necessary to keep notifying us. If you need to use the capability right away you can point your app code at your branch

**Comment by fooofei** [comment]
@dnwe 
sorry about  keep notifying .
i am working at a company, the company used the main repo code, not allow my forked private repo code, so I respect the pull request merged to main repo and pulish a new version.
I have 40 days to reach that goal.  

Have passed 30 days after first pr #2773.

I have left about 10 days, so I have another pr #2807 to reach that goal

**Review by dnwe — APPROVED** [review]
Thanks for working on these changes, I had a chat with @hindessm earlier today and we agreed that this more-targetted PR makes the most sense to go forward with

**Comment by dnwe** [comment]
Released in [v1.43.0](https://github.com/IBM/sarama/releases/latest)

**Pull request merged**
