### PR TITLE
Clean up some typos and docs/help mistakes

### PR DESCRIPTION
**Pull request by hindessm**
Fix obsolete reference to `ioutil.Discard` in docs.
Fix duplication of defaults in `tools/kafka-producer-performance` help output (flag output already includes the defaults without explicitly documenting them).
Fix some typos spotted while reading the code.

### CODE REVIEW

**Comment by dnwe** [comment]
@hindessm thanks! We should probably also enable the misspell golangci-lint checker

**Review by dnwe — APPROVED** [review]

**Comment by dnwe** [comment]
@hindessm interesting, not changed by your PR but it looks like the ubi default package set has seemingly changed overnight and the docker image used by the FV tests no longer has timezone files:
> kafka-4_1      | 2023-07-23T07:10:43.693653327Z java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
etc.

**Comment by hindessm** [comment]
More puzzling is that the ubi image has tzdata package installed *but* is missing the /usr/share/zoneinfo files that the tzdata package contains.

**Comment by hindessm** [comment]
I've pushed a fix - `microdnf reinstall tzdata`.

**Comment by hindessm** [comment]
Sadly I don't think that fix alone was sufficient...

**Comment by hindessm** [comment]
It needed `microdnf install tzdata-java` too.

**Comment by dnwe** [comment]
Thanks!

**Pull request merged**
